import { check, sleep } from 'k6';
import http from 'k6/http';

export const options = {
    scenarios: {
        smokeTest: {
            executor: 'constant-vus', // control how k6 schedules VUs and iterations. 
            vus: 3, // for smoke test, keep it at 2, 3, max 5 VUs
            duration: '10s', //  duration of the test
            gracefulStop: '0s', // do not wait for iterations to finish in the end
            tags: { test_type: 'smoke-test' }, // extra tags for the metrics generated by this scenario
            exec: 'smokeTest', // the function this scenario will execute
        },
        stressTest: {
            executor: 'ramping-vus', // control how k6 schedules VUs and iterations. 
            startVUs: 0, 
            startTime: '10s', // time offset since the start of the test to start the scenario
            stages: [
                { duration: '10s', target: 10 },
                { duration: '30s', target: 100 },
                { duration: '10s', target: 0 },
              ],
            gracefulRampDown: '0s',
            tags: { test_type: 'stress-test' }, // extra tags for the metrics generated by this scenario
            exec: 'stressTest', // the function this scenario will execute
        }
    }
};

export function setup() {
    const payload = {
        "events": [
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            },
            {
                "name": "event1",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "click",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-0000-0000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event2",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "ui_event",
                        "version": "1.0.0",
                        "parameters": {
                            "etype": "track",
                            "event_time": 123
                        }
                    },
                    {
                        "schema": "booking",
                        "version": "1.0.0",
                        "parameters": {
                            "booking_code": "00000000-0000-00000000-000000000000",
                            "speak": "meow",
                            "price": 1.1
                        }
                    }
                ]
            },
            {
                "name": "event3",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "pax"
                        }
                    }
                ]
            },
            {
                "name": "event4",
                "event_time": 123,
                "entities": [
                    {
                        "schema": "search",
                        "version": "1.0.0",
                        "parameters": {
                            "search_term": "p"
                        }
                    }
                ]
            }
        ]
    }

    return {payload: payload}
}

export function smokeTest (data) {
    const res = http.post('http://127.0.0.1:8081/api/events/track', JSON.stringify(data.payload), {
        headers: { 'Content-Type': 'application/json' },
    });
    check(res, { 'status was 200': (r) => r.status == 200 });

  // console.log(JSON.stringify(response.message));

  sleep(1);
};

export function stressTest (data) {
    const res = http.post('http://127.0.0.1:8081/api/events/track', JSON.stringify(data.payload), {
        headers: { 'Content-Type': 'application/json' },
    });
    check(res, { 'status was 200': (r) => r.status == 200 });
    
    sleep(1);
  };

  export function teardown(data) {
    
  }