# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Test
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    
    - name: Build binary
      run: go build -v

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Copy to S3
      run: |
        ls .
        mkdir artifacts
        cp ./event-gateway artifacts
        cp -R ./bootstrap artifacts
        aws s3 sync ./artifacts ${{ vars.S3_BUCKET }}artifacts/event-gateway